apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-practica-1
  labels:
    lab: uno
spec:
  replicas: 3
  selector:
    matchLabels:
      lab: uno
  template:
    metadata:
      labels:
        lab: uno
    spec:
      containers:
      - name: app-uno
        image: cachac/kube-labs